name: live_score
description: Live score app

publish_to: "none"

version: 1.0.1+6

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  hexcolor: ^3.0.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
